<!DOCTYPE html>
<html>
<head>
  <title>HTML -> PDF</title>
  <meta charset="utf-8" />
  <link href="style.css" rel="stylesheet" type="text/css" />
</head>
<body>
<h1>Заявление</h1>
<p>
  <span class="itext">Offer</span> <span class="description"> to be a slave </span>
</p>
<table>
  <tr>
    <th class="label">FirstName</th>
    <td>${firstName}</td>
  </tr>
  <tr>
    <th>LastName</th>
    <td>${lastName}</td>
  </tr>
</table>
</body>
</html>