<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <title>Спасибо за регистрацию</title>
    <style>
        h1 {
            color: cadetblue;
        }
        h2 {
            color: red;
        }
    </style>
</head>
<body>
<h1>Прошу проймти по мсмсылке:</h1>
<img src="https://i.ytimg.com/vi/33yzHbxGn0M/maxresdefault.jpg" alt="">
<h2><a href="${server_url}/confirm?code=${confirm_code}">Пройдите по ссылке, пожалуйсмста</a></h2>
</body>
</html>
