<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"/>
  <meta http-equiv="X-UA-Compatible" content="ie=edge"/>
  <link rel="stylesheet" href="pdf_pattern.css" type="text/css"/>
  <title>Document</title>
</head>
<body>
<h3>Offer</h3>
<p>${firstName}</p>
<p>${lastName}</p>
<p>You are my slave now =) !</p>
</body>
</html>